temperature:
  flags:        #flags for individual points [index, flag]
    - [747, 3]
    - [38480, 3]

  ranges:      #flags for ranges [beginning index, end index, flag]
    - [68072, 68073, 4]

conductivity:
  flags:
    - [126, 4]
    - [2251, 4]
    - [65435, 4]
    - [80520, 4]
  ranges:
    - [15925, 15937, 4]
    - [68072, 68073, 4]
pressure:
  flags:
    - [68073, 4]
  ranges:
    - [68072, 68073, 4]

